[scripts]
#测试类脚本
#NodeQuality
node_quality = "bash <(curl -sL run.NodeQuality.com)"
#融合怪测试
fusion_test = "bash <(curl -sL bash.spiritlhl.net/ecs)"
#IP质量
ip_quality = "bash <(curl -sL Check.Place) -I" #IP质量，交互界面

network_quality = "bash <(curl -sL Check.Place) -N" #网络质量，交互界面
yabs = "bash <(curl -sL yabs.sh)" #yabs
bench = "bash <(curl -sL bench.sh)" #benchmark
super_bench = "bash <(curl -sL git.io/superbench.sh)" #superbench
super_trace = "bash <(curl -sL raw.githubusercontent.com/oooldking/script/master/supertrace.sh)" #supertrace
unlock_test = "bash <(curl -sL Media.Check.Place)" #解锁检测
return_route = "bash <(curl -sL raw.githubusercontent.com/zhanghanyun/backtrace/main/install.sh)" #回程路由
nws_sh = "bash <(curl -sL nws.sh)" #nws


#硬件类测试
dedicated_benchmark = "bash <(curl -sL git.io/ceshi)"
disk_write_test = "bash <(curl -sL raw.githubusercontent.com/NodeSeekDev/NodeScriptKit/refs/heads/main/shell_scripts/hardware_info/disk_test.sh)"
lemon_bench_full="bash <(curl -sL raw.githubusercontent.com/LemonBench/LemonBench/main/LemonBench.sh) --full"
lemon_bench_fast="bash <(curl -sL raw.githubusercontent.com/LemonBench/LemonBench/main/LemonBench.sh) --fast"
unix_bench = "bash <(curl -sL github.com/teddysun/across/raw/master/unixbench.sh)"
memory_check = "bash <(curl -sL raw.githubusercontent.com/uselibrary/memoryCheck/main/memoryCheck.sh)"

[[menus]]
id = "test_tool"
title = "测试工具"
sub_menus = [
  "node_quality",
  "fusion_test",
  "ip_quality",
  "network_quality",
  "yabs",
  "bench",
  "super_bench",
  "unlock_test",
  "return_route",
  "super_trace",
  "nws_sh",

  'dedicated_benchmark',
  'lemon_bench_full',
  'lemon_bench_fast',
  'unix_bench',
  'disk_write_test',
  'memory_check',
]

[[menus]]
id = "node_quality"
title = "NodeQuality"
script = "node_quality"

[[menus]]
id = "fusion_test"
title = "融合怪"
script = "fusion_test"

[[menus]]
id = "ip_quality"
title = "IP质量"
script = "ip_quality"

[[menus]]
id = "network_quality"
title = "网络质量"
script = "network_quality"

[[menus]]
id = "yabs"
title = "YABS"
script = "yabs"

[[menus]]
id = "bench"
title = "Bench"
script = "bench"

[[menus]]
id = "super_bench"
title = "Super Bench"
script = "super_bench"

[[menus]]
id = "unlock_test"
title = "解锁检测"
script = "unlock_test"

[[menus]]
id = "return_route"
title = "回程路由[结果版]"
script = "return_route"

[[menus]]
id = "super_trace"
title = "回程路由[节点版]"
script = "super_trace"

[[menus]]
id = "nws_sh"
title = "综合测速"
script = "nws_sh"

[[menus]]
id = "dedicated_benchmark"
title = "独服基准脚本"
script = "dedicated_benchmark"

[[menus]]
id = "disk_write_test"
title = "硬盘写入测试"
script = "disk_write_test"

[[menus]]
id = "memory_check"
title = "超售测试"
script = "memory_check"


[[menus]]
id = "lemon_bench_full"
title = "LemonBench[完整版]"
script = "lemon_bench_full"

[[menus]]
id = "lemon_bench_fast"
title = "LemonBench[快速版]"
script = "lemon_bench_fast"

[[menus]]
id = "unix_bench"
title = "UnixBench"
script = "unix_bench"
