[scripts]
#重装系统
reinstall = "bash <(curl -sL raw.githubusercontent.com/NodeSeekDev/NodeScriptKit/refs/heads/main/shell_scripts/system_reinstall/reinstall.sh)"
installnet = "bash <(curl -sL raw.githubusercontent.com/NodeSeekDev/NodeScriptKit/refs/heads/main/shell_scripts/system_reinstall/installnet.sh)"
osmutation = "bash <(curl -sL raw.githubusercontent.com/LloydAsp/OsMutation/main/OsMutation.sh)"

[[menus]]
id = "system_reinstall"
title = "重装系统"
sub_menus = [
  "reinstall",
  "installnet",
  "osmutation",
]

#重装系统
[[menus]]
id = "reinstall"
title = "Reinstall"
script = "reinstall"

[[menus]]
id = "installnet"
title = "InstallNET.sh"
script = "installnet"

[[menus]]
id = "osmutation"
title = "OsMutation"
script = "osmutation"