[scripts]
#系统管理
kernel_network_optimizer = "bash <(curl -Lso- git.io/kernel.sh)"
dns_unlock = "bash <(curl -sL raw.githubusercontent.com/Jimmyzxk/DNS-Alice-Unlock/refs/heads/main/dns-unlock.sh)"
add_zram = "bash <(curl -sL raw.githubusercontent.com/spiritLHLS/addzram/main/addzram.sh)"
add_swap = "bash <(curl -sL raw.githubusercontent.com/spiritLHLS/addswap/main/addswap.sh)"

manage_services = "bash <(curl -sL nsk-35i.pages.dev/shell_scripts/system_manage/manage_services.sh)"
terminal_setup = "bash <(curl -sL nsk-35i.pages.dev/shell_scripts/system_manage/terminal_setup.sh)"


[[menus]]
id = "system_manage"
title = "系统管理"
sub_menus = [
  'manage_services',
  'kernel_network_optimizer',
  'dns_unlock',
  'add_zram',
  'add_swap',
  'terminal_setup',
]

[[menus]]
id = "manage_services"
title = "系统&用户服务管理"
script = "manage_services"

[[menus]]
id = "kernel_network_optimizer"
title = "内核与网络优化"
script = "kernel_network_optimizer"

[[menus]]
id = "dns_unlock"
title = "一键修改解锁DNS"
script = "dns_unlock"

[[menus]]
id = "add_zram"
title = "addZram"
script = "add_zram"

[[menus]]
id = "add_swap"
title = "addSwap"
script = "add_swap"

[[menus]]
id = "terminal_setup"
title = "Terminal美化&优化历史记录"
script = "terminal_setup"