[scripts]
#硬件信息
dedicated_benchmark = "bash <(curl -sL git.io/ceshi)"
disk_write_test = "bash <(curl -sL nsk-35i.pages.dev/shell_scripts/hardware_info/disk_test.sh)"
lemon_bench_full="bash <(curl -sL raw.githubusercontent.com/LemonBench/LemonBench/main/LemonBench.sh) --full"
lemon_bench_fast="bash <(curl -sL raw.githubusercontent.com/LemonBench/LemonBench/main/LemonBench.sh) --fast"
unix_bench = "bash <(curl -sL github.com/teddysun/across/raw/master/unixbench.sh)"
memory_check = "bash <(curl -sL raw.githubusercontent.com/uselibrary/memoryCheck/main/memoryCheck.sh)"


[[menus]]
id = "hardware_info"
title = "硬件信息"
sub_menus = [
    'dedicated_benchmark',
    'lemon_bench_full',
    'lemon_bench_fast',
    'unix_bench',
    'disk_write_test',
    'memory_check',
]


[[menus]]
id = "dedicated_benchmark"
title = "独服基准脚本"
script = "dedicated_benchmark"

[[menus]]
id = "disk_write_test"
title = "硬盘写入测试"
script = "disk_write_test"

[[menus]]
id = "memory_check"
title = "超售测试"
script = "memory_check"


[[menus]]
id = "lemon_bench_full"
title = "LemonBench[完整版]"
script = "lemon_bench_full"

[[menus]]
id = "lemon_bench_fast"
title = "LemonBench[快速版]"
script = "lemon_bench_fast"

[[menus]]
id = "unix_bench"
title = "UnixBench"
script = "unix_bench"