[scripts]
#应用部署
app_bt = "bash <(curl -sL download.bt.cn/install/install_panel.sh) ed8484bec"
app_aapanel = "bash <(curl -sL www.aapanel.com/script/install_7.0_en.sh)"
app_1panel = "bash <(curl -sL resource.1panel.pro/quick_start.sh)"
app_nezha = "bash <(curl -sL raw.githubusercontent.com/nezhahq/scripts/refs/heads/main/install.sh)"
app_warp = "bash <(curl -sL gitlab.com/fscarmen/warp_unlock/-/raw/main/unlock.sh)"
app_aria2 = "bash <(curl -sL raw.githubusercontent.com/ToyoDAdoubiBackup/doubi/master/aria2.sh)"
app_alist = "bash <(curl -sL nsk-35i.pages.dev/sh/app_deployment/alist_manager.sh)"
app_aurora = "bash <(curl -sL raw.githubusercontent.com/Aurora-Admin-Panel/deploy/main/install.sh)"


[[menus]]
id = "app_deployment"
title = "应用部署"
sub_menus = [
  'app_bt',
  'app_aapanel',
  'app_1panel',
  'app_nezha',
  'app_warp',
  'app_alist',
  'app_aria2',
  'app_aurora',
]

[[menus]]
id = "app_bt"
title = "宝塔面板[官方版]"
script = "app_bt"

[[menus]]
id = "app_aapanel"
title = "Aapanel面板[官方版]"
script = "app_aapanel"

[[menus]]
id = "app_1panel"
title = "1Panel面板[官方版]"
script = "app_1panel"

[[menus]]
id = "app_nezha"
title = "nezha面板[官方版]"
script = "app_nezha"

[[menus]]
id = "app_warp"
title = "warp解锁"
script = "app_warp"

[[menus]]
id = "app_aria2"
title = "aria2下载器"
script = "app_aria2"

[[menus]]
id = "app_alist"
title = "alist网盘"
script = "app_alist"

[[menus]]
id = "app_aurora"
title = "极光面板"
script = "app_aurora"